### ISSUE TITLE
same bug as solid-file-client

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-content-manager#13]
for `name` appearing more than once in `fullname`
see pull request #7  last commit https://github.com/jeff-zucker/solid-ide/pull/7/commits/e5a874bbe9f2f9870ed7c3e5e94323afad180dbe

I have difficulty to make a new pull not including the previous one. May be I should have deleted my fork before making a new commit ?

**Comment by jeff-zucker** [comment]
Oh, yeah, I had that problem with a PR I submitted to someone else.  I ended up deleting my fork, re-forking, then submitting the PR.  There may be an easier way, but I don't know about it.  If it's easier, I can just cut and paste this time.

**Comment by bourgeoa** [comment]
Ok I deleted and recreated the fork and made a new pull and issue.

Le jeu. 28 mars 2019 à 19:59, Jeff Zucker <notifications@github.com> a
écrit :

**Comment by bourgeoa** [comment]
see PR #14
