### ISSUE TITLE
update to solid-file-client.bundle.js

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-content-manager#16]
Jeff I have made the upgrade to replace solid-file-client.js by solid-file-client.bundle.js.
There seem to be no error left.
You can check at https://bourgeoa.github.io/solid-ide/
If you agree I will push a new pull

Can I delete the the pull #7 and #14 which will not be relevant anymore ?

**Comment by jeff-zucker** [comment]
Thanks so much for your work I'm traveling for the next few days and won't be able to get to it till about Wednesday but really appreciate what you've done
