### ISSUE TITLE
SolidHandler.replace() as a SolidFileClient.delete() followed by SolidFileClient.create() is dangerous

### ISSUE THREAD

**Issue by robmccoll** [jeff-zucker/solid-content-manager#18]
Reproduce:
- Edit your profile card on the community pod server via solid-ide (being careful to not create invalid turtle).
- Note that saving succeeds at deleting your card and then everything goes a little sideways haha.

Recovery:
- Manually rebuild your card via curl.

It could perhaps be argued that the node-solid-server shouldn't just let you do this, but I guess it is conformant to the spec.

**Comment by jeff-zucker** [comment]
Thanks much for this and your other reports.  I and my collaborators are working on a completely revamped solid-file-client which will replace most of how solid-ide works, including this.  We hope to release it in early September.

**Comment by bourgeoa** [comment]
solved
. using PUT and the new solid-file-client v1.0.0
. temporarily forbidding to edit the profile card (need to check we have a valid turtle)
