### ISSUE TITLE
add zip/unzip of file/folder with acl

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-content-manager#23]
@jeff-zucker 
I saw you commit my last PR #21 which was tested on https://www.bourgeoa.ga/solid-ide-v1
It was working seemingly very well
I wanted to test it on https://bourgeoa.github.io/solid-ide but did not realized it was added to the open PR #21 

Problem : it did not work on github.io with the following error : 

> window.mimer is not afunction

 I don't know why

I found that replacing the mimer CDN with a version in dist/ solved the problem. That is PR #22 

**Some comments on zip/unzip** 
- I took the inspiration from Otto-AA solid-file-manager (he zipp without acl and unzip acl without control)
- I amended his work to zip with acl and unzip with control on acl
- control on acl are the following : (done using solid-file-client rdf.query)
. it is a valid turtle (this is made by N3)
. it must have either webId or everybody with 'Control'
. acl 'accessTo' is valid

**and now**
. As the actual version is broken I am commiting PR #22 
. I can amend or revert everything
. to check that unzip works correctly I uploaded zip file including different bad type of acl.

**Comment by jeff-zucker** [comment]
Do you have full rights to merge commits?  Perhaps I should just stay out
of the way and let you merge when you're ready.
