### ISSUE TITLE
No cookies on NSS5

### ISSUE THREAD

**Issue by leinue** [jeff-zucker/solid-content-manager#3]
Hi, thanks for ur great work on solid-ide.But after I upgraded NSS to 5.0 beta-5, I found that I couldn't use solid-ide to access private folders. I checked the network request and found no cookies. What is the reason?
For testing, u can visit solid.authing.cn

**Comment by jeff-zucker** [comment]
As we discussed in the chat room, this issue is not specific to Solid-IDE, it's an issue with the server and/or solid-auth-client.
