### ISSUE TITLE
Do I need to add the solid-ide as a trusted app to be able to login?

### ISSUE THREAD

**Issue by phochste** [jeff-zucker/solid-content-manager#31]
When I login I can see all my folders in the left panel of the solid-ide and I can see an authenticated version of my pod in the middle panel. In the middle panel I can access all my files. But, in the left panel I can only access my public files.

When I try to access a private container I get `SFCFetchError 403 - Make sure that the origin of your app is authorized for your pod`. What is the App URL I need to add to my trusted applications?

For the rest the application is fantastic: vi, emacs, atom like!

**Comment by jeff-zucker** [comment]
Yes, you should manually add it to your profile.  If you are using a local version add localhost with the port number.  If you are using the public webapp version at https://jeff-zucker.github.io/solid-ide/, Add the origin "https://jeff-zucker.github.io".

**Comment by jeff-zucker** [comment]
And give it all rights so you can delete and change sharing with the ide.

**Comment by phochste** [comment]
Yes that works! Thanks
