### ISSUE TITLE
Host via github.io

### ISSUE THREAD

**Issue by Otto-AA** [jeff-zucker/solid-content-manager#8]
Is a particular reason, why this isn't hosted via github.io? I personally prefer this, as this makes sure, that the code used is actually the same as the one in the repository (so it is up to date and definitely not hosted with bad intentions).

As far as I know, this could easily be changed in the repository settings.

**Comment by bourgeoa** [comment]
It is already available at https://jeff-zucker.github.io/solid-ide/

**Comment by Otto-AA** [comment]
Oh, my bad. And it is even stated in the Readme o.o
